import { cn } from '@/lib/utils';

/**
 * The client's YUVA mark.
 *
 * Served as a file from `public/` rather than inlined as JSX: the long shadow
 * is a few hundred offset copies of each letter, which would bury any component
 * that carried it. It is generated by `scripts/generate-logo.mjs` — edit that,
 * not the SVG.
 *
 * Sized by height, because the mark is a fixed 502 x 204 and only ever needs to
 * sit on a line of text.
 */
export function Logo({ className, alt = 'Yuva' }: { className?: string; alt?: string }) {
  return (
    <img
      src="/logo.svg"
      /*
       * "Yuva", not "Yuva Polyprint" — the mark itself reads YUVA, and every
       * place it appears is followed by "Polyprint". Naming the whole company
       * here would have a screen reader announce "Polyprint" twice.
       */
      alt={alt}
      className={cn('w-auto select-none', className)}
      draggable={false}
    />
  );
}
